name: 'torrtv'
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jarvisnexus/torrtv:latest
    container_name: torrtv
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TORRSERVER_URL=http://localhost:5665
    restart: always
